#!/usr/bin/python

#
# Use the typeMap defined in ArchetypesGenerator.ArchetypesGenerator to print
# a list of of the types natively supported by ArchGenXML
#

import ArchetypesGenerator

typeMap = ArchetypesGenerator.ArchetypesGenerator.typeMap
widgetMap = ArchetypesGenerator.ArchetypesGenerator.widgetMap

keys = typeMap.keys ()
keys.sort ()

for type in keys:
   
    widget = widgetMap.get (type, '')
    
    print "%s --> %s (%s)" % (type, typeMap[type]['field'], widget)

    for (prop, value) in typeMap[type]['map'].items ():
        print '    ', prop, ':', value

    print
